blank_issues_enabled: true  # option allows you to show or hide the Create a blank issue choice when users select New(blank) issue
contact_links:
  - name: View Carson Blog
    url: https://carsonslovoka.github.io/
    about: Enjoy!
